### ISSUE TITLE
Issue with Redirect uri

### ISSUE THREAD

**Issue by JoeCherry** [xinranxiao/meteor-accounts-spotify#2]
I'm having trouble with using "http://localhost:3000/_oauth/spotify?close" as the redirect uri. I keep getting the following error:
INVALID_CLIENT: Invalid redirect URI

**Comment by xinranxiao** [comment]
Did you register this URL on the Spotify developer site?

**Comment by JoeCherry** [comment]
Yes I have it listed as my redirect URI.

**Comment by xinranxiao** [comment]
Open your browser in incognito mode, go to your app, and click your login button. Can you copy & paste the URL that you see on the popup that appears?

**Comment by JoeCherry** [comment]
https://accounts.spotify.com/en/authorize?response_type=code&client_id=cc16d738aec44ae6a4d904ae41800d0d&redirect_uri=http:%2F%2Flocalhost:3000%2F_oauth%2Fspotify%3Fclose&state=eyJsb2dpblN0eWxlIjoicG9wdXAiLCJjcmVkZW50aWFsVG9rZW4iOiJSTlE3TWFqaHlLY3lDd3BkXzBWMjI4Y25ldHFhS1NHaXEtSV9ZQmNSTHB0IiwiaXNDb3Jkb3ZhIjpmYWxzZX0&scope=user-read-email#_=_

**Comment by xinranxiao** [comment]
Double-check that you have the correct redirect URL listed on the Spotify developer site for the correct key pair. I just tested the library on a clean api key pair/the same redirect and it works fine. Make sure you hit the save button after you type in the redirect URI on the Spotify website.

**Comment by JoeCherry** [comment]
I got it working. I added "http://" in front of the redirect URI on Spotify and that seemed to work.
