### ISSUE TITLE
Redirect uri

### ISSUE THREAD

**Issue by newswim** [xinranxiao/meteor-accounts-spotify#3]
can i use localhost/_oauth/spotify?close for development? I'm getting the popup callback window but the page is saying unauthorized.

**Comment by xinranxiao** [comment]
yes, just use something like `http://localhost:3000/_oauth/spotify?close`

**Comment by rkstar** [comment]
i've set my redirect uri to `http://localhost:3000/_oauth/spotify?close` in my app at spotify, but i'm still getting the `INVALID_CLIENT: ....` error

do i need to have this route configured in my meteor app?

**Comment by xinranxiao** [comment]
No, you do not need to have this route configured. However, you do need the correct ServiceConfigurations set. View this if you are still having trouble setting it up (it's a full end-to-end example of spotify accounts + api):

https://github.com/xinranxiao/meteor-spotify-web-api/tree/master/examples/1

**Comment by pmwisdom** [comment]
Same things happening to me. Tried every version of localhost:3000 with that url and nothing seems to work for the redirect url.

**Comment by pmwisdom** [comment]
Nevermind! I didn't know there was a save button at the bottom of the page!

**Comment by pors** [comment]
I think you can close this. As @pmwisdom said, the Spotify "My Application" page keeps the "save" button below the fold :)
