### ISSUE TITLE
Log out current Spotify user

### ISSUE THREAD

**Issue by matthlavacka** [xinranxiao/meteor-accounts-spotify#4]
First of all, thank you for providing this package and example app, that you made.

I was wondering if there is any way to implement log out?

**Comment by xinranxiao** [comment]
http://docs.meteor.com/#/full/meteor_logout

You can logout like any other type of account (password, google oauth, facebook oauth, etc.)

**Comment by matthlavacka** [comment]
thanks!

**Comment by pors** [comment]
Meteor.logout() does log out the user, but how can you revoke the oAuth access? Let's say a user wants to no longer give an app access to his/her Spotify account.

**Comment by xinranxiao** [comment]
@pors Sorry for the late reply. So apparently this isn't supported yet: https://github.com/spotify/web-api/issues/126
